### ISSUE TITLE
Reset Text Input

### ISSUE THREAD

**Issue by iamneaz** [pnp/powerapps-designtoolkit#13] opened 2023-01-23 11:51 UTC
How can I reset the text value of a text input with its default value?

**Comment by geoffroff** [comment] 2023-03-09 08:16
I believe this has been fixed in 1.0.0.7.
<pre>Set(defaults,
    Patch(defaults,
        {
            primaryColorHex: Match(JSON(defaults.primaryColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch,
            primaryColorTransparentHex: Match(JSON(defaults.primaryColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch&"4d",
            secondaryColorHex: Match(JSON(defaults.secondaryColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch,
            disabledColorHex: Match(JSON(defaults.disabledColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch,
            backgroundColorHex: Match(JSON(defaults.backgroundColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch,
            elementBackgroundColorHex: Match(JSON(defaults.elementBackgroundColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch,
            `textColorHex: Match(JSON(defaults.textColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch`,
            errorColorHex: Match(JSON(defaults.errorColor,JSONFormat.IgnoreUnsupportedTypes),"#[a-fA-F0-9]{6}").FullMatch
        }
    )
)</pre>

**Comment by geoffroff** [comment] 2023-03-09 08:36
You should just reset the MD component on screen.
<pre>Reset(cmp_MD_Textinput_1)</pre>

**Comment by PowerRobin** [comment] 2023-03-10 22:18
Could reproduce, but not reliably fix the error. Seems to be a PowerApps issue 🤔

**Closed by PowerRobin** 2023-03-10 22:18 UTC
